LaboratoryProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

blog/urls.py
from .views import index, about, article, user
from django.urls import path, include

app_name = 'blog'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('article/<int:article_id>/', article, name='article'),
    path('user/<int:user_id>', user, name='user'),
]

users/urls.py
from django.urls import path, include
from .views import profile, login, register, logout

app_name = "users"

urlpatterns = [
    path("profile/", profile, name="profile"),
    path("", login, name="login"),
    path("register/", register, name="register"),
    path("logout/", logout, name="logout"),

]

blog/models.py
from users.models import User
from django.db import models

SHORT_TEXT_LEN = 200
# Create your models here
class Article(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField(upload_to='static/articles_image', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_short_text(self):
        if len(self.text) > SHORT_TEXT_LEN:
            return self.text[:SHORT_TEXT_LEN]
        else: return self.text

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.first_name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    profile_image = models.ImageField(upload_to='static/users_profile_images', default='static/users_profile_images/defaultIconProfile.png' ,null=True, blank=True)
    back_image = models.ImageField(upload_to='static/users_background_images', default='static/users_background_images/defaultIconBack.png', null=True, blank=True)

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Comment
        fields = ['text']

users/forms.py
from django.contrib.auth.forms import  AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from users.models import User

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(label='First Name', widget=forms.TextInput(attrs={'placeholder': 'Ваш ник на портале'}))
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'placeholder': 'Ваш логин'}))
    email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Повторите пароль'}))
    class Meta:
        model = User
        fields = ('first_name','username','email','password1','password2')


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Ваш логин'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Введите пароль'
    }))
    class Meta:
        model = User
        fields = ('username', 'password')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={}))
    profile_image = forms.ImageField(widget=forms.FileInput(attrs={}))
    back_image = forms.ImageField(widget=forms.FileInput(attrs={}))

    class Meta:
        model = User
        fields = ('first_name', 'profile_image', 'back_image')

blog/views.py
from audioop import reverse

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from .models import Article, Comment
from users.models import User
from .forms import CommentForm

# Create your views here.

def index(request):
    context = {
        'articles': Article.objects.all()
    }
    return render(request,'blog/home.html', context)

def article(request, article_id):
    article = get_object_or_404(Article, id=article_id)

    if request.method == "POST":
        form = CommentForm(request.POST)  # Получаем данные из формы

        if form.is_valid():  # Проверяем валидность формы
            if request.user.is_authenticated:  # Проверяем авторизацию пользователя
                comment = form.save(commit=False)  # Сохраняем, но пока не записываем в БД
                comment.article = article  # Присваиваем статью
                comment.user = request.user  # Присваиваем пользователя
                comment.save()  # Сохраняем комментарий в БД
                return redirect('blog:article', article_id=article_id)  # Перенаправление после успешного добавления
            else:
                return redirect('users:login')

    else:
        form = CommentForm()

    context = {
        'article': article,
        'form': form,
        'comments': Comment.objects.filter(article=article)
    }
    return render(request,'blog/article.html', context)

def about(request):
    return render(request,'blog/about.html')

def user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    context = {
        'articles': Article.objects.filter(user=user),
        'user': user
    }
    return render(request,'blog/user.html', context)

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, HttpResponseRedirect, reverse, get_object_or_404
from django.contrib import auth
from django.core.mail import send_mail
from blog.models import Article
from blog.views import article
from .forms import UserRegistrationForm, UserLoginForm, UserProfileForm

# Create your views here.
@login_required(login_url='users:login')
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES )
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)
        articles = Article.objects.filter(user=request.user)
    context = {
        'form': form,
        'articles': articles
    }
    return render(request, 'users/profile.html', context)

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            data = """
                            Здравствуйте!

                            Спасибо за регистрацию на портале "&copy;Мой Сайт™"

                            --Это автоматическое сообщение, не нужно на него отвечать.
                                """
            send_mail('Добро пожаловать на "&copy;Мой Сайт™"!', data, from_email="misha5555548@yandex.ru",
                      recipient_list=[request.user.email], fail_silently=False)
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/registration.html', context)

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                data = """
                Здравствуйте!

                Вы только что вошли в свой аккаунт на портале "&copy;Мой Сайт™"
                Если это были не вы, то мы ничего не можем поделать)))

                --Это автоматическое сообщение, не нужно на него отвечать.
                    """
                send_mail('Добро пожаловать на "&copy;Мой Сайт™"!', data, from_email="",recipient_list = [request.user.email], fail_silently=False)
                return HttpResponseRedirect(reverse('blog:index'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('users:login'))

blog/templates/blog/article.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    {% tailwind_css %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'priject-image/site-icon.png' %}" type="image/x-icon">  
    <title>{{ article.title }}</title>
  </head>

  <body class="bg-gray-700">
    <!-- Навигационная панель -->
    <div class="fixed top-0 left-0 w-full text-center py-4 bg-gray-800 z-50 h-16">
      <ul class="inline-flex space-x-8">
          <li><a href="{% url 'blog:index' %}" class="text-white text-xl sm:text-3xl">Домой</a></li>
          <li><a href="{% url 'blog:about' %}" class="text-white text-xl sm:text-3xl">О нас</a></li>
          <li><a href="#" class="text-white text-xl sm:text-3xl">Контакты</a></li>
          <li><a href="{% url 'users:profile' %}" class="text-white text-xl sm:text-3xl">Аккаунт</a></li>
    </ul>
    </div>

    <!-- Основной контент, оформленный как статьи -->
    <div class="pt-16 container px-4 static max-w-md mx-auto md:max-w-6xl">
      <hr class="bg-amber-950 mb-6">
        <h1 class="text-center text-2xl sm:text-4xl text-white">{{ article.title }}</h1>
        <p class="mt-6 mb-5 sm:text-2xl text-white">{{ article.text }}</p>
        <a href="{% url 'blog:user' article.user.id %}" class="text-blue-700">Автор: {{ article.user.first_name }}</a>
        <div class="my-8 flex flex-row gap-6"><h1 class=" text-2xl sm:text-4xl text-left text-white">Комментарии</h1>  
            <button id="toggleFormButton" class="text-xl sm:text-2xl px-2 py-0.5 text-white rounded transition ease-in-out delay-150 
            bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300">Добавить</button> </div>
    
    
    <div id="editForm" class="my-6 mx-auto bg-white p-6 rounded-lg shadow-lg transform transition-all duration-500 opacity-0 scale-95 hidden mt-8 max-w-md z-50">
      <h2 class="text-xl sm:text-2xl font-semibold mb-4">Ваш комментарий</h2>
      <form action="{% url 'blog:article' article.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-4">
          {{ form.text }}
        </div>
        <div class="flex justify-end">
          <button type="submit" class="text-xl sm:text-2xl px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition">Отправить</button>
        </div>
      </form>
    </div>
    
    
        {% for comment in comments %}
    <div class="my-6 max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-7xl">
        <div class="flex">
            <div class="flex flex-col items-center">
                <a href="{% url 'blog:user' comment.user.id %}">
                    <img class="w-16 h-16 sm:w-24 sm:h-24 rounded-full border-4 border-white object-cover" src="{{ comment.user.profile_image.url }}" alt="User avatar">
                </a>
                <p class="mt-1 text-xs sm:text-base text-blue-700">{{ comment.user.first_name }}</p>
            </div>
            <div class="p-8 flex-1">
                <p class="mt-2 text-slate-500 text-left">{{ comment.text }}</p>
            </div>
        </div>
    </div>
{% endfor %}
    
    
    
    
    <script>
    const toggleButton = document.getElementById('toggleFormButton');
    const editForm = document.getElementById('editForm');

    toggleButton.addEventListener('click', () => {
      if (editForm.classList.contains('hidden')) {
        editForm.classList.remove('hidden');
        // Используем setTimeout для плавного перехода после удаления 'hidden'
        setTimeout(() => {
          editForm.classList.remove('opacity-0', 'scale-95');
          editForm.classList.add('opacity-100', 'scale-100');
        }, 10);
      } else {
        editForm.classList.add('opacity-0', 'scale-95');
        editForm.classList.remove('opacity-100', 'scale-100');
        // Добавляем 'hidden' после завершения анимации
        setTimeout(() => {
          editForm.classList.add('hidden');
        }, 500); // Должно совпадать с duration-500
      }
    });
    
    document.addEventListener("DOMContentLoaded", function() {
    const form = document.querySelector("#comment-form");
    form.addEventListener("submit", function() {
        form.reset();  // Очищает все поля формы после отправки
    });
});
  </script>
    
    </div>
    
    
    
    
    
    
    

  <footer class="fixed bottom-0 left-0 w-full bg-gray-800 shadow-inner z-50">
      <div class="container mx-auto px-4 py-4 text-center text-white">
        &copy; 2024 Мой Сайт. Все права защищены.
      </div>
    </footer>

    <!-- Отступ для основного контента, чтобы не перекрывался футером -->
    <div class="pb-16"></div>
  
  </body>
</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>

users/templates/users/profile.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    {% tailwind_css %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'priject-image/site-icon.png' %}" type="image/x-icon">  
    <title>{{ user.first_name }}</title>
  </head>

  <body class="bg-gray-700 min-h-screen flex flex-col">
  
  <!-- Навигационная панель -->
    <div class="fixed top-0 left-0 w-full bg-gray-800 text-white z-50">
        <div class="flex justify-between items-center px-4 py-4 h-16">
            <!-- Логотип сайта, видимый только на маленьких экранах -->
            <div class="block lg:hidden text-center flex-1">
                <span class="text-white text-2xl sm:text-3xl font-semibold">Мой Сайт</span>
            </div>

            <!-- Иконка меню для маленьких экранах с анимацией -->
            <div class="absolute right-4 lg:hidden">
                <button id="menu-button" class="focus:outline-none transition transform duration-300 ease-in-out">
                    <svg class="w-8 h-8 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7" />
                    </svg>
                </button>
            </div>

            <!-- Меню навигации для больших экранов -->
            <ul class="hidden lg:flex space-x-8 flex-1 justify-center transition duration-300">
                <li><a href="{% url 'blog:index' %}" class="text-white text-xl">Домой</a></li>
                <li><a href="{% url 'blog:about' %}" class="text-white text-xl">О нас</a></li>
                <li><a href="#" class="text-white text-xl">Контакты</a></li>
                <li><a href="{% url 'users:profile' %}" class="text-white text-xl">Аккаунт</a></li>
            </ul>
        </div>

        <!-- Мобильное меню с анимацией -->
        <ul id="mobile-menu" class="hidden flex-col items-center text-center space-y-4 mt-4 pb-4 bg-gray-800 lg:hidden transition-all duration-300 ease-in-out overflow-hidden">
            <li><a href="{% url 'blog:index' %}" class="text-white text-xl transition ease-in-out delay-130 bg-gray-800 hover:bg-blue-600 px-5 py-0.5 rounded-3xl duration-300">Домой</a></li>
            <li><a href="{% url 'blog:about' %}" class="text-white text-xl transition ease-in-out delay-130 bg-gray-800 hover:-translate-y-1 hover:scale-110 hover:bg-blue-600 px-5 py-0.5 rounded-3xl duration-300">О нас</a></li>
            <li><a href="#" class="text-white text-xl transition ease-in-out delay-130 bg-gray-800 hover:bg-blue-600 px-5 py-0.5 rounded-3xl duration-300">Контакты</a></li>
            <li><a href="{% url 'users:profile' %}" class="text-white text-xl transition ease-in-out delay-130 bg-gray-800 hover:bg-blue-600 px-5 py-0.5 rounded-3xl duration-300">Аккаунт</a></li>
        </ul>
    </div>

  <!-- Основной контент -->
  <div class="pt-16 flex-grow container mx-auto px-4">
  <hr class="bg-amber-950 mb-6">

    <!-- Фоновое изображение профиля -->
    <div class="relative">
      <img class="w-full h-64 object-cover rounded-lg" src="{{ user.back_image.url }}?{{ user.back_image }}" alt="Фоновое изображение профиля">
      
      <!-- Секция профиля: изображение, ник, кнопка -->
      <div class="absolute bottom-0 left-1/2 transform -translate-x-1/2 translate-y-1/2 bg-white p-4 rounded-lg shadow-lg flex items-center space-x-4">
        <!-- Изображение профиля -->
        <img class="w-16 h-16 sm:w-24 sm:h-24 rounded-full border-4 border-white object-cover" src="{{ user.profile_image.url }}?{{ user.profile_image }}" alt="Изображение профиля">
        
        <!-- Никнейм пользователя -->
        <span class="text-2xl font-semibold text-gray-800">{{ user.first_name }}</span>
          
        
        <!-- Кнопка для редактирования профиля -->
        <div class="absolute -bottom-2 sm:-bottom-4 -left-2"><button id="toggleFormButton" class="px-2 py-0.5 text-white rounded transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300">
          Изменить
        </button></div>
          <a class="absolute -bottom-2 sm:-bottom-4 right-2 bg-red-700 text-white rounded px-2 py-0.5 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-red-900 duration-300" href="{% url 'users:logout' %}">Выйти</a> 
          
      </div>
    </div>
<h1 class="text-center sm:text-left text-4xl font-bold text-white mt-14 mb-5 sm:mt-10 sm:mb-10">Статьи <a href="#" class="">+</a></h1>
  <!-- Форма для изменения логина и пароля -->
    <div id="editForm" class="mx-auto bg-white p-6 rounded-lg shadow-lg transform transition-all duration-500 opacity-0 scale-95 hidden mt-8 max-w-md z-50">
      <h2 class="text-2xl font-semibold mb-4">Данные профиля</h2>
      <form action="{% url 'users:profile' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-4">
          <label for="{{ form.first_name.id_for_label }}" class="block text-gray-700">Имя пользователя</label>
          {{ form.first_name }}
        </div>  
        
        <div class="mb-4">
          <label for="{{ form.profile_image.id_for_label }}" class="block text-gray-700">Изображение профиля</label>
          {{ form.profile_image }}
        </div>  
        <div class="mb-4">
          <label for="{{ form.back_image.id_for_label }}" class="block text-gray-700">Изображение фона</label>
          {{ form.back_image }}
        </div>  
          
          
        <div class="flex justify-end">
          <button type="submit" class="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition">Сохранить</button>
        </div>
      </form>
    </div>
  
      
    {% for article in articles %}
    <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-7xl">
      <div class="md:flex">
        <div class="md:shrink-0">
          <img class="h-48 w-full object-cover md:h-full md:w-64" src="{{ article.image.url }}" alt="Modern building architecture">
        </div> 
        <div class="p-8">
          <div class="uppercase tracking-wide text-sm text-indigo-500 font-semibold"></div>
          <a href="{% url 'blog:article' article.id %}" class="block mt-1 text-lg leading-tight font-medium text-black hover:underline">{{ article.title }}</a>
          <p class="mt-2 text-slate-500">{{ article.get_short_text }}...</p>
          <a href="{% url 'blog:user' article.user.id %}" class="mt-3 text-blue-700">Автор: {{ article.user.first_name }}</a>  
        </div>
      </div>
    </div>
    {% endfor %}
      
    

    <!-- Другой контент страницы -->
    
  </div>

  <!-- Футер -->
  <footer class="fixed bottom-0 left-0 w-full bg-gray-800 shadow-inner z-50 h-16">
    <div class="container mx-auto px-4 py-4 text-center text-white">
      &copy; 2024 Мой Сайт. Все права защищены.
    </div>
  </footer>

  <!-- Отступ для основного контента, чтобы не перекрывался футером -->
  <div class="pb-16"></div>

  <!-- JavaScript для управления формой -->
  <script>
    const toggleButton = document.getElementById('toggleFormButton');
    const editForm = document.getElementById('editForm');

    toggleButton.addEventListener('click', () => {
      if (editForm.classList.contains('hidden')) {
        editForm.classList.remove('hidden');
        // Используем setTimeout для плавного перехода после удаления 'hidden'
        setTimeout(() => {
          editForm.classList.remove('opacity-0', 'scale-95');
          editForm.classList.add('opacity-100', 'scale-100');
        }, 10);
      } else {
        editForm.classList.add('opacity-0', 'scale-95');
        editForm.classList.remove('opacity-100', 'scale-100');
        // Добавляем 'hidden' после завершения анимации
        setTimeout(() => {
          editForm.classList.add('hidden');
        }, 500); // Должно совпадать с duration-500
      }
    });
    
    
  </script>
  
  <script>
        document.getElementById("menu-button").onclick = function() {
            const mobileMenu = document.getElementById("mobile-menu");
            // Добавляем/убираем класс hidden и задаем max-height для анимации
            if (mobileMenu.classList.contains("hidden")) {
                mobileMenu.classList.remove("hidden");
                mobileMenu.style.maxHeight = mobileMenu.scrollHeight + "px";
            } else {
                mobileMenu.style.maxHeight = "0";
                setTimeout(() => {
                    mobileMenu.classList.add("hidden");
                }, 300); // Время должно совпадать с transition duration
            }
        };
    </script>

</body>
</html>

users/templates/users/registration.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    {% tailwind_css %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Регистрация</title>
  </head>

  <body class="bg-gray-700">
    <!-- Навигационная панель -->
    <div class="fixed top-0 left-0 w-full text-center py-4 bg-gray-800 z-50 h-16">
      <ul class="inline-flex space-x-8">
        <li><a href="{% url 'blog:index' %}" class="text-white text-3xl">Домой</a></li>
        <li><a href="{% url 'blog:about' %}" class="text-white text-3xl">О нас</a></li>
        <li><a href="#" class="text-white text-3xl">Контакты</a></li>
        <li><a href="{% url 'users:profile' %}" class="text-white text-3xl">Аккаунт</a></li>
      </ul>
    </div>

    <!-- Основной контент, оформленный как статьи -->
    <div class="pt-16 container mx-auto px-4">
        <hr class="bg-amber-950 mb-6">
        <h1 class="my-6 text-4xl text-center text-white">Регистрация</h1>
        
        <!-- Центрирование формы с помощью flex -->
        <div class="flex justify-center">
            <form class="bg-white shadow-lg rounded-lg text-center grid grid-cols-1 gap-6 p-8 max-w-md w-full" action="{% url 'users:register' %}" method="post">
                {% csrf_token %}
                
                {% if form.non_field_errors %}
                <div class="shadow-lg rounded-lg bg-purple-200 px-4 py-2">{{ form.non_field_errors }}</div>
                {% endif %}
                
                <!-- Поле: Ник на портале -->
                <div class="text-center">
                    <label for="id_first_name" class="block text-gray-700 mb-2">Ник на портале</label>
                    {{ form.first_name }}
                </div>
                
                <!-- Поле: Адрес электронной почты -->
                <div class="text-center">
                    <label for="id_email" class="block text-gray-700 mb-2">Адрес электронной почты</label>
                    {{ form.email }}
                </div>
                
                <!-- Поле: Логин -->
                <div class="text-center">
                    <label for="id_username" class="block text-gray-700 mb-2">Логин</label>
                    {{ form.username }}
                </div>
                
                <!-- Поле: Пароль -->
                <div class="text-center">
                    <label for="id_password1" class="block text-gray-700 mb-2">Пароль</label>
                    {{ form.password1 }}
                </div>
                
                <!-- Поле: Подтверждение пароля -->
                <div class="text-center">
                    <label for="id_password2" class="block text-gray-700 mb-2">Подтверждение пароля</label>
                    {{ form.password2 }}
                </div>
                
                <!-- Кнопка отправки формы -->
                <div>
                    <button class="w-full px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition" type="submit">Зарегистрироваться</button>
                </div>
                
                <!-- Ссылка на страницу входа -->
                <p class="mt-4">
                    Уже есть аккаунт?
                    <a class="text-blue-500 hover:underline" href="{% url 'users:login' %}">Войти</a>
                </p>
            </form>
        </div>
    </div>

  <footer class="fixed bottom-0 left-0 w-full bg-gray-800 shadow-inner z-50">
      <div class="container mx-auto px-4 py-4 text-center text-white">
        &copy; 2024 Мой Сайт. Все права защищены.
      </div>
    </footer>

    <!-- Отступ для основного контента, чтобы не перекрывался футером -->
    <div class="pb-16"></div>
  
  </body>
</html>

users/templates/users/test.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Site</title>
    {% tailwind_css %}
</head>
<body>
  <h1>My site</h1>
  <p>Hello world!</p>
</body>
</html>